### ISSUE TITLE
Xcode 12.2 MacOS 11..0.1 objc4-781 编译失败

### ISSUE THREAD

**Issue by ceekay1991** [LGCooci/objc4_debug#11]
objc4_debug-master/objc4-781/runtime/objc-runtime-new.h:290:5: error: static_assert failed due to requirement 'bucketsMask >= ((unsigned long long)140737454800896ULL)' "Bucket field doesn't have enough bits for arbitrary pointers."
    static_assert(bucketsMask >= MACH_VM_MAX_ADDRESS, "Bucket field doesn't have enough bits for arbitrary pointers.");
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
5 warnings and 1 error generated.

Xcode 12.2
MacOS 11..0.1
objc4-781 编译失败

**Comment by LGCooci** [comment]
Xcode12.2 目前无法编译 等最新open source我会及时编译更新发自我的iPhone------------------ 原始邮件 ------------------发件人: ceekay1991  <notifications@github.com>发送时间: 2020年12月9日 16:05收件人: LGCooci/objc4_debug <objc4_debug@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[LGCooci/objc4_debug] Xcode 12.2 MacOS 11..0.1 objc4-781 编译失败 (#11)
objc4_debug-master/objc4-781/runtime/objc-runtime-new.h:290:5: error: static_assert failed due to requirement 'bucketsMask >= ((unsigned long long)140737454800896ULL)' "Bucket field doesn't have enough bits for arbitrary pointers."
static_assert(bucketsMask >= MACH_VM_MAX_ADDRESS, "Bucket field doesn't have enough bits for arbitrary pointers.");
^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
5 warnings and 1 error generated.
Xcode 12.2
MacOS 11..0.1
objc4-781 编译失败

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/LGCooci/objc4_debug/issues/11",
"url": "https://github.com/LGCooci/objc4_debug/issues/11",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by shilihuan** [comment]
@LGCooci 大神啥时候更新啊

**Comment by LGCooci** [comment]
哈哈 坐等apple发自我的iPhone------------------ 原始邮件 ------------------发件人: shilihuan  <notifications@github.com>发送时间: 2020年12月11日 15:12收件人: LGCooci/objc4_debug <objc4_debug@noreply.github.com>抄送: Cooci <cooci_tz@163.com>, Mention <mention@noreply.github.com>主题: 回复：[LGCooci/objc4_debug] Xcode 12.2 MacOS 11..0.1 objc4-781 编译失败 (#11)
@LGCooci 大神啥时候更新啊

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/LGCooci/objc4_debug/issues/11#issuecomment-743019992",
"url": "https://github.com/LGCooci/objc4_debug/issues/11#issuecomment-743019992",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
