### ISSUE TITLE
可以运行在真机调试吗？

### ISSUE THREAD

**Issue by z-wade** [LGCooci/objc4_debug#13]

**Comment by LGCooci** [comment]
不可以哦发自我的iPhone------------------ 原始邮件 ------------------发件人: ChenJunzhi  <notifications@github.com>发送时间: 2021年2月22日 11:23收件人: LGCooci/objc4_debug <objc4_debug@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[LGCooci/objc4_debug] 可以运行在真机调试吗？ (#13)


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/LGCooci/objc4_debug/issues/13",
"url": "https://github.com/LGCooci/objc4_debug/issues/13",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
